### ISSUE TITLE
Consider providing bibtex-tidy

### ISSUE THREAD

**Issue by sbrugman** [scipy-conference/scipy_proceedings#742]
There is this tool [bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy) that helps formatting and checking bib files, improving the overal quality (e.g. prevent duplicates in DOI and keys, consistent ordering of keys). We could consider providing this tool as a utility to authors.

The author instructions contain pointers on using bib, namely:
> All citations that have DOIs should include those DOIs in the paper's references section, see [mybib.bib](https://github.com/scipy-conference/scipy_proceedings/blob/2022/papers/00_bibderwalt/mybib.bib).

Moreover, scoobies provides a [`check references` command](https://buffy.readthedocs.io/en/latest/responders/check_references.html). This feature would be complementary.

One additional sentence could point towards this utility. 
## Possible implementation
Alternatively, the [`pre-commit`](https://pre-commit.com/) hook seems like a way to help authors even further, without having tight integration (pre-commit points to the repository). 

`.pre-commit-config.yaml`:
```
repos:
-   repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.8.5
    hooks:
    - id: bibtex-tidy
      args:
      - '--curly'
      - '--numeric'
      - '--tab'
      - '--align=13'
      - '--duplicates=key,doi'
      - '--no-escape'
      - '--sort-fields=title,shorttitle,author,year,month,day,journal,booktitle,location,on,publisher,address,series,volume,number,pages,doi,isbn,issn,url,urldate,copyright,category,note,metadata'
      - '--no-remove-dupe-fields'
```
 

Format and check `.bib` files in the repository:
`pre-commit run --all-files`

Happy to contribute a PR if this feature is deemed desirable.
